### ISSUE TITLE
proto files

### ISSUE THREAD

**Issue by marcelocecin** [ericnelson0/GoHBot#2]
hi there

is possible to use the *.proto files to decode the POST

thank you

**Comment by ericnelson0** [comment]
Yep, I was messing around with automatically logging raid values every x amount of minutes.

Anything with 
`proto.Protos.ResponseEnvelope.deserializeBinary(new Uint8Array(body));`
is using the *.proto files to decode the protobuf reply from an rpc call.

**Comment by marcelocecin** [comment]
how can I decode the code at #4 with GetEventsResponse.proto ?
1: 29
2: 1464664130
4: "\037\213\b\000\000\000\000\000\000\000\023\330\333\272d\331\005-\211\aW\230\001w\352\232A\v\000\000\000"
5: 1
7: 1

thank you

**Comment by ericnelson0** [comment]
Not sure what you ran that through, but it looks like GetEventsResponse is an array of GameEvents

`
message GetEventsResponse {
   repeated GameEvent game_event = 1;
}
`
and GameEvent is defined as
```
message GameEvent {
   optional string id = 1 [default = ""];
   optional int32 priority = 2 [default = 0];
   optional string name_key = 3 [default = ""];
   optional string summary_key = 4 [default = ""];
   optional string desc_key = 5 [default = ""];
   optional string image = 6 [default = ""];
   optional GameEventType type = 7 [default = SCHEDULED];
   optional BucketItem keycard_entry_cost = 8;
   optional int64 keycard_duration = 9 [default = 0];
   repeated GameEventInstance instance = 10;
   optional GameEventStatus status = 12 [default = EVENTLOCKED];
   optional CampaignElementIdentifier campaign_element_identifier = 13;
   optional SquadType squad_type = 14 [default = SQUADEVENT];
   optional string preview_key = 15 [default = ""];
   optional string review_key = 16 [default = ""];
   optional GameEventUILocation ui_location = 17 [default = GAMEEVENTUILOCATIONTRIALS];
   optional string icon = 18 [default = ""];
   optional bool defensive_squad_usage_cost_enabled = 19 [default = false];
   repeated ContextualMessageGroup encounter_message = 20;
   repeated Environment environment = 21;
   optional string desc_key_unit_criteria_met = 22 [default = ""];
}
```

Sometimes the payload is compressed in a ResponseEnvelope (check the `message.content_encoding`)

**Comment by danhenke** [comment]
hi.. can I ask how you managed to extract the proto files?

**Comment by marcelocecin** [comment]
@ericnelson0 and how to decompress the payload ?

**Comment by danhenke** [comment]
Its gzip encoded. Not sure what you're using but gzdecode works in php.

**Comment by marcelocecin** [comment]
i'm trying to call this command: ./protoc --decode=InitialDataResponse --proto_path=protos InitialDataResponse.proto < Data.bin but i'm facing the error: Enum type "Protos.UnitTier" has no value named "TIER01"
